[package]
name = "hodl"
version = "1.0.0"
authors = []

[addresses]

HOGLET = "0x17aecc0a267c77a70f51db8070f504bce55d64de886e675b52bd9143729897d9"
hoglet_hodl = "0xc39791f9e014d335741680f41c5c7ba9181e7b26f27a17e18bd4778fbc763ec3"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosToken]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]

