[package]
name = "hoglet_core"
version = "1.0.0"
authors = []

[addresses]

HOG = "0x3ec6be8be7d00c5e778a76ea9a3cf8650ccb7cb0e6fcce36653beed63198cc9f"
hoglet_core = "0x0d6be8c7019e2fd473233437665e44e16967b5f4aa8ce8a991aa8c7b5e406da4"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosToken]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token"

[dependencies.buffer]
git = "https://github.com/hoglet-DAO/Buffer_contracts.git"
rev = "main"
subdir = "mainnet"

[dependencies.hoglet_dao]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "mainnet/dao_factory"

[dependencies.amm]
git = "https://github.com/hoglet-DAO/amm_contracts.git"
rev = "main"
subdir = "mainnet"

[dependencies.hodl]
git = "https://github.com/hoglet-DAO/hoglet_launcher.git"
rev = "main"
subdir = "mainnet/hodl_fa"

[dev-dependencies]

