[package]
name = "hoglet_core"
version = "1.0.0"
authors = []

[addresses]

MIDNIGHT = "0xa6df8835a9ff8f3f84e7a5997547f83dc6fb0e805706c51035f82fdd685d3567"
hoglet_core = "0xa6df8835a9ff8f3f84e7a5997547f83dc6fb0e805706c51035f82fdd685d3567"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosToken]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token"

[dependencies.buffer]
git = "https://github.com/hoglet-DAO/Buffer_contracts.git"
rev = "main"
subdir = "testnet"

[dependencies.hoglet_dao]
local = "../dao_factory"

[dependencies.amm]
local = "../amm"

[dependencies.hodl]
local = "../hodl"

[dev-dependencies]

