[package]
name = "hoglet_core"
version = "1.0.0"
authors = []

[addresses]

HOGLET = "0x17aecc0a267c77a70f51db8070f504bce55d64de886e675b52bd9143729897d9"
hoglet_core = "0x5d660f79970951e2e375e05b437cba455b2d60fc440ddd70d87db464a44a91d5"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.AptosToken]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token"

[dependencies.buffer]
git = "https://github.com/hoglet-DAO/Buffer_contracts.git"
rev = "main"
subdir = "testnet"

[dependencies.hoglet_dao]
git = "https://github.com/hoglet-DAO/DAO_contracts.git"
rev = "main"
subdir = "testnet/dao_factory"

[dependencies.amm]
git = "https://github.com/hoglet-DAO/amm_contracts.git"
rev = "main"
subdir = "testnet"

[dependencies.hodl]
git = "https://github.com/hoglet-DAO/hoglet_launcher.git"
rev = "main"
subdir = "testnet/hodl_fa"

[dev-dependencies]

